// YouTutu PWA — HTML Document Renderer
// Generates a self-contained HTML reference document from processed video data.

import { APP_NAME } from './constants.js';

/**
 * Render a complete self-contained HTML document.
 * @param {Object} data
 * @param {string} data.title
 * @param {string} data.author
 * @param {string} data.publishDate
 * @param {number} data.lengthSeconds
 * @param {string} data.description
 * @param {string} data.id
 * @param {Array<{startTime: number, title: string}>} data.chapters
 * @param {Array<{timestamp: number, dataUrl: string, chapterTitle: string|null}>} data.keyframes
 * @param {Array<{start: number, text: string, formattedTime: string}>} data.transcript
 * @param {string|null} data.summary
 * @returns {string} Complete HTML document string
 */
export function renderHTML(data) {
  const {
    title, author, publishDate, lengthSeconds, description, id,
    chapters, keyframes, transcript, summary,
  } = data;

  const duration = formatDuration(lengthSeconds);
  const date = formatDate(publishDate);
  const youtubeUrl = `https://www.youtube.com/watch?v=${id}`;
  const escapedTitle = escapeHtml(title);
  const escapedAuthor = escapeHtml(author);
  const escapedDesc = escapeHtml(description);

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapedTitle} — ${APP_NAME} Notes</title>
<style>
${getDocumentCSS()}
</style>
</head>
<body>

<header>
  <h1>${escapedTitle}</h1>
  <div class="meta">
    <span class="author">${escapedAuthor}</span>
    ${date ? `<span class="separator">·</span><span class="date">${date}</span>` : ''}
    <span class="separator">·</span>
    <span class="duration">${duration}</span>
    <span class="separator">·</span>
    <a href="${youtubeUrl}" class="source-link" target="_blank" rel="noopener">Watch on YouTube</a>
  </div>
</header>

<main>
${renderSummarySection(summary)}
${renderDescriptionSection(escapedDesc)}
${renderChaptersSection(chapters)}
${renderKeyframesSection(keyframes)}
${renderTranscriptSection(transcript)}
</main>

<footer>
  <p>Generated by ${APP_NAME} on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
</footer>

</body>
</html>`;
}

function renderSummarySection(summary) {
  if (!summary) {
    return `<section class="summary">
  <h2>Summary</h2>
  <p class="placeholder">AI summary not available for this document.</p>
</section>`;
  }

  return `<section class="summary">
  <h2>Summary</h2>
  <div class="summary-content">${escapeHtml(summary).replace(/\n/g, '<br>')}</div>
</section>`;
}

function renderDescriptionSection(description) {
  if (!description || description.length < 20) return '';

  const isLong = description.length > 300;
  const content = description.replace(/\n/g, '<br>');

  if (isLong) {
    return `<details class="description">
  <summary><h2>Description</h2></summary>
  <div class="description-content">${content}</div>
</details>`;
  }

  return `<section class="description">
  <h2>Description</h2>
  <div class="description-content">${content}</div>
</section>`;
}

function renderChaptersSection(chapters) {
  if (!chapters?.length) return '';

  const items = chapters.map((ch) =>
    `    <li><span class="chapter-time">${formatTimestampForDoc(ch.startTime)}</span> ${escapeHtml(ch.title)}</li>`
  ).join('\n');

  return `<section class="chapters">
  <h2>Chapters</h2>
  <ol class="chapter-list">
${items}
  </ol>
</section>`;
}

function renderKeyframesSection(keyframes) {
  if (!keyframes?.length) return '';

  const figures = keyframes.map((kf) => {
    const time = formatTimestampForDoc(kf.timestamp);
    const caption = kf.chapterTitle
      ? `${time} — ${escapeHtml(kf.chapterTitle)}`
      : time;

    return `  <figure class="keyframe">
    <img src="${kf.dataUrl}" alt="Frame at ${time}" loading="lazy">
    <figcaption>${caption}</figcaption>
  </figure>`;
  }).join('\n');

  return `<section class="keyframes">
  <h2>Key Frames</h2>
  <div class="keyframe-grid">
${figures}
  </div>
</section>`;
}

function renderTranscriptSection(transcript) {
  if (!transcript?.length) return '';

  const paragraphs = transcript.map((seg) =>
    `    <p><time class="ts">${seg.formattedTime}</time> ${escapeHtml(seg.text)}</p>`
  ).join('\n');

  return `<details class="transcript">
  <summary><h2>Full Transcript</h2></summary>
  <div class="transcript-content">
${paragraphs}
  </div>
</details>`;
}

function getDocumentCSS() {
  return `
:root {
  --bg: #ffffff;
  --surface: #f8f8fa;
  --text: #1d1d1f;
  --text2: #6e6e73;
  --accent: #e94560;
  --border: #e5e5ea;
  --font: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #1a1a2e;
    --surface: #16213e;
    --text: #e8e8ed;
    --text2: #98989d;
    --accent: #e94560;
    --border: #38384a;
  }
}
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
html { font-size: 16px; }
body {
  font-family: var(--font);
  background: var(--bg);
  color: var(--text);
  line-height: 1.6;
  max-width: 48rem;
  margin: 0 auto;
  padding: 2rem 1.5rem;
}
header { margin-bottom: 2rem; border-bottom: 1px solid var(--border); padding-bottom: 1.5rem; }
h1 { font-size: 1.5rem; line-height: 1.3; margin-bottom: 0.5rem; }
.meta { font-size: 0.875rem; color: var(--text2); display: flex; flex-wrap: wrap; align-items: center; gap: 0.5rem; }
.separator { opacity: 0.4; }
.source-link { color: var(--accent); text-decoration: none; }
.source-link:hover { text-decoration: underline; }
main > section, main > details { margin-bottom: 2rem; }
h2 { font-size: 1.125rem; margin-bottom: 0.75rem; display: inline; }
details > summary { cursor: pointer; list-style: none; }
details > summary::-webkit-details-marker { display: none; }
details > summary h2::after { content: ' ▸'; font-size: 0.875rem; opacity: 0.5; }
details[open] > summary h2::after { content: ' ▾'; }
.summary-content { background: var(--surface); padding: 1rem 1.25rem; border-radius: 8px; line-height: 1.7; }
.placeholder { color: var(--text2); font-style: italic; }
.description-content { color: var(--text2); font-size: 0.9375rem; line-height: 1.6; }
.chapter-list { padding-left: 1.5rem; }
.chapter-list li { margin-bottom: 0.25rem; font-size: 0.9375rem; }
.chapter-time { font-variant-numeric: tabular-nums; color: var(--accent); font-weight: 500; margin-right: 0.5rem; }
.keyframe-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 1rem; }
.keyframe { background: var(--surface); border-radius: 8px; overflow: hidden; }
.keyframe img { width: 100%; height: auto; display: block; }
.keyframe figcaption { padding: 0.5rem 0.75rem; font-size: 0.8125rem; color: var(--text2); }
.transcript-content { margin-top: 0.75rem; }
.transcript-content p { margin-bottom: 0.5rem; font-size: 0.9375rem; }
.ts { font-variant-numeric: tabular-nums; color: var(--accent); font-weight: 500; margin-right: 0.5rem; font-size: 0.8125rem; }
footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border); font-size: 0.75rem; color: var(--text2); text-align: center; }
@media (max-width: 480px) {
  body { padding: 1rem; }
  h1 { font-size: 1.25rem; }
  .keyframe-grid { grid-template-columns: 1fr; }
}`;
}

function escapeHtml(str) {
  if (!str) return '';
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function formatDuration(seconds) {
  if (!seconds) return '';
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = seconds % 60;

  if (h > 0) return `${h}h ${m}m`;
  if (m > 0) return `${m}m ${s}s`;
  return `${s}s`;
}

function formatDate(dateStr) {
  if (!dateStr) return '';
  try {
    return new Date(dateStr).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  } catch {
    return dateStr;
  }
}

function formatTimestampForDoc(seconds) {
  const s = Math.floor(seconds);
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  const sec = s % 60;

  if (h > 0) {
    return `${h}:${String(m).padStart(2, '0')}:${String(sec).padStart(2, '0')}`;
  }
  return `${m}:${String(sec).padStart(2, '0')}`;
}
